---
- name: Info Faktual Paket
  package_facts:
    manager: auto

- name: Info os-release
  command: cat /etc/os-release
  register: os_rel
  changed_when: false

- name: Kernel
  command: uname -r
  register: kernel
  changed_when: false

- name: Hostname
  command: hostname
  register: host
  changed_when: false

- name: Sumber APT aktif
  shell: |
    cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources 2>/dev/null \
      | grep -vE '^\s*(#|$)' || true
  register: apt_sources
  changed_when: false
  failed_when: false
