# -l localhost -> mesin lokal
# -l vm -> test dari ssh
# -l all -> keduanya
#


[blankon_local]
localhost ansible_connection=local

[blankon_vm]
#vm-qa ansible_host=IPSEREVER ansible_user=vboxuser


[blankon:children]
blankon_local
blankon_vm
